delete pm_prepare
delete pm_outdoor_product
delete pm_outdoor_road
delete pm_outdoor_apply
delete pm_contract
delete pm_contract_fb
delete pm_project
delete pm_work_detail
delete pm_work_head
delete pm_task_detail
delete pm_task_head
delete pm_task_feedback_detail
delete pm_task_feedback_head
delete pm_task_cc_detail
delete pm_task_cc_head
delete pm_receive_detail
delete pm_receive_head
delete pm_deposit
delete pm_deposit_return
delete pm_js_detail
delete pm_js_head
delete pm_pay_detail
delete pm_pay_head
